name: CondenseReforged
version: '${project.version}'
main: crosis47.minecraft.condense.CondensePlugin
api-version: '1.21.11'
authors: [ crosis47 ]
description: Paper plugin with a command to condense items into other items.

commands:
  condense:
    description: Condense configured items into other items
    permission: condense.use
    usage: "/condense [reload]"

permissions:
  condense.use:
    description: Allows use of /condense
    default: true

  condense.reload:
    description: Allows reloading the plugin config
    default: op